### ISSUE TITLE
OSX download

### ISSUE THREAD

**Issue by snogcel** [dashpay/dashcore-node#11]
bitcore-node-dash is failing when attempting to retrieve OSX binaries, will get fixed soon (or disable automatic download for OSX)

**Comment by viest** [comment]
Yeah, it solved my problem.

**Comment by akfranco** [comment]
This issue was moved to dashevo/dashcore-node#32

**Comment by nmarley** [comment]
We're in the process of merging this repo w/the dashevo one, and we're removing the download entirely from that and making it a separate dependency.

This work should be done by early next week at the latest. If this is needed right now, please use the  `develop` branch of this repo: https://github.com/dashevo/dashcore-node
