### ISSUE TITLE
Cannot install permission issue

### ISSUE THREAD

**Issue by zarulizham** [dashpay/dashcore-node#23]
Hello, I cannot install this repo said that permission error. Please refer my question in Stackoverflow

https://stackoverflow.com/questions/47391205/npm-install-failed-due-to-permission-denied

**Comment by fanatid** [comment]
`scripts/download` is not executable
you should install with `--ignore-scripts`,
then `chmod +x ./scripts/download`
and `dos2unix ./scripts/download`

totally unusable package right now

**Comment by zarulizham** [comment]
Thank you sir for your suggestions. I will try later on 😄

**Comment by zarulizham** [comment]
Hi @fanatid, currently I already install `npm install -g bitcore-node-dash --ignore-scripts`, 

but when is it to `chmod +x ./scripts/download` and `dos2unix ./scripts/download`?

**Comment by fanatid** [comment]
https://github.com/dashevo/bitcore-node-dash/issues/11#issuecomment-349661023

**Comment by zarulizham** [comment]
Thanks for the URL. I am able to install without any error. But how to start the service?

I tried using `bitcore-node-dash start` but returns `bitcore-node-dash: command not found`

**Comment by fanatid** [comment]
You should read all thread instead single comments.
https://github.com/dashevo/bitcore-node-dash/issues/11#issuecomment-349624619

**Comment by zarulizham** [comment]
Alright I'm done with `bitcore-node-dash`. But when try to install `Insight UI Dash`, The command return error as below

<img width="515" alt="screen shot 2017-12-12 at 11 36 09 am" src="https://user-images.githubusercontent.com/10229855/33866290-acb83eae-df30-11e7-83b7-74d5d6f1f0d0.png">

**Comment by akfranco** [comment]
This issue was moved to dashevo/dashcore-node#37

**Comment by nmarley** [comment]
Your original issue is related to the download script. We're in the process of merging this repo w/the dashevo one, and we're removing the download entirely from that and making DashCore a separate dependency.

This work should be done by early next week at the latest. If this is needed right now, please use the  `develop` branch of this repo: https://github.com/dashevo/dashcore-node
