### ISSUE TITLE
Export keys and move wallet

### ISSUE THREAD

**Issue by Serrenima** [dashpay/dashcore-node#24]
I want clone wallet on my PC from server, I think is't not work with conflict?

Thanks.

**Comment by knoxcard** [comment]
Here is the dash-cli command line way to do it...

dash-cli dumpprivkey [dash-wallet-address]

**Example:**
dash-cli dumpprivkey Xr3eJquX3sKPaAxqvXDto1H9VYEgY8zygo

**Comment by Serrenima** [comment]
I didn't want dump address key, I want dump wallet.

**Comment by akfranco** [comment]
This issue was moved to dashevo/dashcore-node#38

**Comment by nmarley** [comment]
This has nothing to do with bitcore-node-dash and the original issue text also doesn't make much sense. Closing.
