### ISSUE TITLE
Merging back changes from bitcore-node

### ISSUE THREAD

**Issue by karelbilek** [dashpay/dashcore-node#5]
Can you please merge changes back from bitcore-node 3.1.3 (and publish the result to npm)?

I am developing MyTrezor, there is a bug fixed in bitcore-node 3.1.3 with mempool, that would help us if it was fixed.

**Comment by karelbilek** [comment]
(We are now adding dash support to mytrezor)

**Comment by schinzelh** [comment]
I'l have a look at it.

**Comment by schinzelh** [comment]
@snogcel I have rebased bitcore-node-dash to bitcore-node-3.1.3. Travis looks good, please release bitcore-node-dash-3.1.3 to npmjs

**Comment by snogcel** [comment]
tnx flare, I've published bitcore-node-dash@3.1.3 to npmjs.

@runn1ng can you please confirm?

**Comment by karelbilek** [comment]
Hello, sorry for ignoring this :(

master_3.1.3 really has the necessary fixes. However, the master_3.1.3 and master started to diverge when I look at it :/ can you please merge. Thanks a lot

Also - note that bitpay started ignoring bitcore development. Since we really needed fixes for segwit (probably not applicable on dash), we started having our own forks

https://github.com/satoshilabs?utf8=%E2%9C%93&q=insight&type=&language=
https://github.com/satoshilabs?utf8=%E2%9C%93&q=bitcore&type=&language=
https://github.com/satoshilabs/bitcoin (<-this is bitcore patchset rebased on latest bitcoin-core)
 
Right now I can't promise we will keep them maintained; for that reason we didn't add them to npm (so it doesn't seem like we are "promising" to maintain) and we are installing everything from github commits; we might change that in the future.

**Comment by akfranco** [comment]
This issue was moved to dashevo/dashcore-node#31

**Comment by nmarley** [comment]
This issue is a bit ancient at this time, and the repo at https://github.com/dashevo/dashcore-node should have the newest changes and be up-to-date with the original BitPay upstream.

We're in the process of merging this repo w/the dashevo one, so should be ok to close this.

**Comment by karelbilek** [comment]
just fyi, since this resurfaced in my mentions

we are in a process of migrating away from bitcore+insight since it is hard to maintain for multiple currencies and we are building an open source coin agnostic indexer + API. So far it does not include frontend explorer

https://github.com/jpochyla/blockbook
