### ISSUE TITLE
TypeError: Address has mismatched network type.

### ISSUE THREAD

**Issue by Ruxiol** [dashpay/dashcore-node#73]
Hello Community!

I forked Dash's code to start a Community project, with learning in mind.

We managed to get all figured out, but this Insight explorer is killing us, and we want to learn basics.

When we start Insight node, it starts ok, we can see explorer website and even blocks with connection.

But if we click on any block or anything else, we get error and all node goes down.

Error that we get on console is

"error: uncaught exception: TypeError: Address has mismatched network type."

 error: uncaught exception: TypeError: Address has mismatched network type.
    at Function.Address._transformBuffer (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/dashcore-lib/lib/address.js:217:11)
    at Function.Address._transformString (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/dashcore-lib/lib/address.js:296:22)
    at Address._classifyArguments (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/dashcore-lib/lib/address.js:116:20)
    at new Address (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/dashcore-lib/lib/address.js:76:19)
    at Object.Address (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/dashcore-lib/lib/address.js:54:12)
    at TxController.transformOutput (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/insight-api/lib/transactions.js:183:28)
    at Array.map (<anonymous>)
    at TxController.transformTransaction (/home/rxc/dashcore-node/mynode/node_modules/@dashevo/insight-api/lib/transactions.js:86:42)
    at /home/rxc/dashcore-node/mynode/node_modules/@dashevo/insight-api/lib/transactions.js:280:16
    at /home/rxc/dashcore-node/node_modules/async/dist/async.js:4617:26

As i understand that has something with networks.js file, where we define networkMagic to match our network.
File is located at /dashcore-node/mynode/node_modules/@dashevo/dashcore-lib/lib/networks.js

From our source code we have this information

pchMessageStart[0] = 0xd6;
pchMessageStart[1] = 0x93;
pchMessageStart[2] = 0xf3;
pchMessageStart[3] = 0x43;
vAlertPubKey = ParseHex("04e807f1caf222eb75de194e8b83c065c89fbce06b60d0968cdc832bd1ce17ef264362b43df7fd9 7cc7a1a38d69d6b7aab3c16cf7a3a9988fa8816c69a6a3016e1");
nDefaultPort = 23506;
nPruneAfterHeight = 100000;

So we changed networkMagic to 0x4693f343, and p2p port 23506

Should we change anything else from here?

addNetwork({
  name: 'livenet',
  alias: 'mainnet',
  pubkeyhash: 0x4c,
  privatekey: 0xcc,
  scripthash: 0x10,
  xpubkey: 0x488b21e,    // 'xpub' (Bitcoin Default)
  xprivkey: 0x488ade4,   // 'xprv' (Bitcoin Default)
  networkMagic: 0xd693f343,
  port: 23506,

Our source code chainparams.cpp for reference
https://github.com/Ruxiol/ruxcryptoRXC/blob/master/src/chainparams.cpp

When i read error again, it says TypeError: Address has mismatched network type, could that be problem somewhere else, some other file?

If someone could help us understand we would be grateful

Could this be the problem? if yes, how can i get those values from my source code
pubkeyhash: 0x4c,
privatekey: 0xcc,
scripthash: 0x10,

Rux, Crypto.ba Community

**Comment by Alex-Werner** [comment]
Hi, 

Yes, If you modified chainparams, you will need to update it everywhere as that's needed for derivation and address generation.

**Comment by Ruxiol** [comment]
Can you put me on right path, im really lost at this stage

As i can imagine, these values are from DASH
pubkeyhash: 0x4c,
privatekey: 0xcc,
scripthash: 0x10,

How can i find these values in my fork?

Please dont mind our ignorance, we are learning stuff

**Comment by Alex-Werner** [comment]
If I don't mistake, it is exactly around theses lines : https://github.com/Ruxiol/ruxcryptoRXC/blob/master/src/chainparams.cpp#L320

You committed in a single commit, without keeping the previous commit structure (not even the previous contributors, not even the base fork), I have no way to check easily what changes you have made, I can't really help you more :/

**Comment by snogcel** [comment]
Hey @Ruxiol a couple things that might help you get pointed in the right direction: 

1) The error message is being thrown here: https://github.com/dashevo/dashcore-lib/blob/v0.19-dev/lib/address.js#L217 -- it's probably having trouble identifying the network type of the address being provided but not sure why exactly.

2) To determine why, I'd suggest taking advantage of the test coverage included in dashcore-lib: https://github.com/dashevo/dashcore-lib/blob/v0.19-dev/test/address.js. If you plug your network info in there it should give you a clearer idea as to why it's failing.

Hope this helps! Good luck

**Comment by Ruxiol** [comment]
@Alex-Werner yea we copied code localy and studied for a long time, then we made some changes and uploaded it back so i understand your confusion, really. We realised what we done, but its to late now.

Thank you both for guidenance, we will try to focus on it and find reason of this bug.

@snogcel  i saw that test part, and after i read your post i realised, yea... we should test it 

:) thank you guys for positivity!

**Comment by Ruxiol** [comment]
I tried some stuff but again it crashes.

Is there a way someone would like to help us finish this properly, we would put some BTC for effort?

**Comment by Ruxiol** [comment]
I have figured out what was the problem.

i just had to convert hexadecimal to decimal, and vice versa, no more nasty bug :)

**Comment by Alex-Werner** [comment]
@Ruxiol Glad you found the solution. Good luck on your educational endeavour. 
Closing this.
